/* All free solid fontawesome icons -> https://fontawesome.com/icons?d=gallery&s=solid&m=free */

import {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faColumns,
    faSearch,
    faTable,
    faTachometerAlt,
    faUser,
    faAsterisk,
    faUserFriends,
    faDatabase,
    faPaperPlane,
    faPager,
    faBan,
    faFeather,
    faBrain,
    faBox,
    faCircle,
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeSolidIcons = {
    faCircle,   
    faBrain,
    faBox,
    faFeather,  
    faBan,
    faPager,    
    faPaperPlane,
    faDatabase,
    faUserFriends,
    faAsterisk,
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faColumns,
    faSearch,
    faTable,
    faTachometerAlt,
    faUser,
};
